import {
  Box,
  Heading,
  Link,
  List,
  ListItem,
  Stack,
  Text,
  theme,
} from '@chakra-ui/react';
import { useEffect } from 'react';

const PrivacyPolicy = () => {

  useEffect(() => {
    window.scrollTo(0, 0);
  }, [])

  return (
    <Box mt={24} ms={64} me={72}>
      <Stack pb={96} color={'white'}>
        <Heading as="h1" size="xl">
          Privacy Policy
        </Heading>
        <Text fontSize="lg" mb={4}>
          Last updated: May 10, 2024
        </Text>
        <Text mb={8}>
          This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
        </Text>
        <Text mb={8}>
          We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.
        </Text>

        <Heading as="h2" size="lg" mb={4}>
          Interpretation and Definitions
        </Heading>
        <Heading as="h3" size="md" mb={2}>
          Interpretation
        </Heading>
        <Text mb={4}>
          The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
        </Text>

        <Heading as="h3" size="md" mb={2}>
          Definitions
        </Heading>
        <List spacing={4} mb={8}>
          <ListItem>
            <Text>
              <strong>• Account</strong> means a unique account created for You to access our Service or parts of our Service.
            </Text>
          </ListItem>
          <ListItem>
            <Text>
              <strong>• Affiliate</strong> means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.
            </Text>
          </ListItem>
          <ListItem>
            <Text>
              <strong>• Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to Quan C.
            </Text>
          </ListItem>
          <ListItem>
            <Text>
              <strong>• Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.
            </Text>
          </ListItem>
          <ListItem>
            <Text>
              <strong>• Country</strong> refers to: Indonesia
            </Text>
          </ListItem>
          <ListItem>
            <Text>
              <strong>• Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.
            </Text>
          </ListItem>
          <ListItem>
            <Text>
              <strong>• Personal Data</strong> is any information that relates to an identified or identifiable individual.
            </Text>
          </ListItem>
          <ListItem>
            <Text>
              <strong>• Service</strong> refers to the Website.
            </Text>
          </ListItem>
          <ListItem>
            <Text>
              <strong>• Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.
            </Text>
          </ListItem>
          <ListItem>
            <Text>
              <strong>• Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).
            </Text>
          </ListItem>
          <ListItem>
            <Text>
              <strong>• Website</strong> refers to Quan C, accessible from{' '}
              <Link href="http://localhost:3000" rel="external nofollow noopener" target="_blank">
                http://localhost:3000
              </Link>
            </Text>
          </ListItem>
          <ListItem>
            <Text>
              <strong>• You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable and as permitted by the Company.
            </Text>
          </ListItem>
        </List>

        <Heading as="h2" size="lg" mb={4}>
          Collecting and Using Your Personal Data
        </Heading>
        <Text mb={8}>
          We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:
        </Text>

        <List spacing={4} mb={8}>
          <ListItem>
            <Text>• Email address</Text>
          </ListItem>
          <ListItem>
            <Text>• First name and last name</Text>
          </ListItem>
          <ListItem>
            <Text>• Phone number</Text>
          </ListItem>
          <ListItem>
            <Text>• Address, State, Province, ZIP code, or other delivery information</Text>
          </ListItem>
          <ListItem>
            <Text>• Payment information</Text>
          </ListItem>
          <ListItem>
            <Text>• Personal information</Text>
          </ListItem>
        </List>

        <Heading as="h2" size="lg" mb={4}>
          Usage Data
        </Heading>
        <Text mb={8}>
          We may also collect information how the Service is accessed and used ("Usage Data"). This Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
        </Text>

        <Heading as="h2" size="lg" mb={4}>
          Tracking Technologies and Cookies
        </Heading>
        <Text mb={8}>
          We use Cookies and similar tracking technologies to track the activity on Our Service and hold certain information. Cookies are files with small amount of data which may include an anonymous unique identifier. Cookies are sent to Your browser from a website and stored on Your device. Other tracking technologies are also used such as beacons, tags and scripts to collect and track information and to improve and analyze Our Service. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service.
        </Text>

        <Heading as="h2" size="lg" mb={4}>
          Use of Your Personal Data
        </Heading>
        <Text mb={8}>
          The Company may use Personal Data for the following purposes:
        </Text>

        <List spacing={4} mb={8}>
          <ListItem>
            <Text>• To provide and maintain Our Service, including to monitor the usage of Our Service.</Text>
          </ListItem>
          <ListItem>
            <Text>• To manage Your Account: to enable You to access and use Our Service, and to provide and delete Your Personal Data and to change the password associated with Your Account.</Text>
          </ListItem>
          <ListItem>
            <Text>• To contact You: To communicate with You in relation to providing and maintaining the Service, such as to respond to Your inquiries, requests, and comments.</Text>
          </ListItem>
          <ListItem>
            <Text>• For the performance of a contract: To provide You with the Service in accordance with any contract You might have with Us.</Text>
          </ListItem>
          <ListItem>
            <Text>• To provide You with news, special offers, and general information about other goods, services, or events which we offer that are similar to those that You have already purchased or enquired about unless You have opted not to receive such information.</Text>
          </ListItem>
          <ListItem>
            <Text>• To manage Your requests: To attend and manage Your requests to Us.</Text>
          </ListItem>
        </List>

        <Heading as="h2" size="lg" mb={4}>
          Retention of Your Personal Data
        </Heading>
        <Text mb={8}>
          The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary tocomply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.
        </Text>

        <Heading as="h2" size="lg" mb={4}>
          Transfer of Your Personal Data
        </Heading>
        <Text mb={8}>
          Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country, or other governmental jurisdiction where the data protection laws may differ than those from Your jurisdiction.
        </Text>

        <Heading as="h2" size="lg" mb={4}>
          Disclosure of Your Personal Data
        </Heading>
        <Text mb={8}>
          Business Transactions
        </Text>
        <Text mb={8}>
          If the Company is involved in a merger, acquisition, or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.
        </Text>

        <Heading as="h2" size="lg" mb={4}>
          Security of Your Personal Data
        </Heading>
        <Text mb={8}>
          The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.
        </Text>

        <Heading as="h2" size="lg" mb={4}>
          Children's Privacy
        </Heading>
        <Text mb={8}>
          Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers.
        </Text>

        <Heading as="h2" size="lg" mb={4}>
          Links to Other Websites
        </Heading>
        <Text mb={8}>
          Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit.
        </Text>

        <Heading as="h2" size="lg" mb={4}>
          Changes to This Privacy Policy
        </Heading>
        <Text mb={8}>
          We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.
        </Text>

        <Heading as="h2" size="lg" mb={4}>
          Contact Us
        </Heading>
        <Text mb={8}>
          If you have any questions about this Privacy Policy, You can contact us:
        </Text>
        <List spacing={4} mb={36}>
          <ListItem>
            <Text>By email: project.quanc@gmail.com</Text>
          </ListItem>
        </List>
      </Stack>
    </Box>
  );
};

export default PrivacyPolicy;